In [66]:
import pandas as pd
df1 = pd.read_csv('movie_code_list_all.csv')
df2 = pd.read_csv('test.csv')

In [67]:
df3 = pd.merge(df1,df2,how='left',on='movieNm')

In [68]:
df2

     Unnamed: 0                          movieNm       1      2     3     4
0             0                              마스터  145162   8.65  5.77  8.10
1             1                   로그 원: 스타워즈 스토리  136868   8.34  7.16  8.44
2             2                             라라랜드  134963   8.90  8.34  8.59
3             3                                씽  144938   8.99  6.71  8.96
4             4                              판도라  132933   8.78  5.92  8.31
5             5                     당신, 거기 있어줄래요  145292   8.80  5.44  8.68
6             6                          너의 이름은.  150198   9.02  7.55  8.75
7             7                       미씽: 사라진 여자  142625   8.53  6.72  8.37
8             8                             패신저스  116233   8.03  5.50  7.95
9             9                              여교사  139673   7.31  6.78  6.61
10           10                                형  142803   8.91  4.55  8.34
11           11                 에곤 쉴레: 욕망이 그린 그림  154307   8.05  6.25  7.93
12           12                        루돌프와 많이있어  153951   8.73  6.38  8.80
13           13  포켓몬 더 무비 XY&Z 「볼케니온 : 기계왕국의 비밀」  152265   8.74  0.00  8.75
14           14                         사랑하기 때문에  140010   8.39  6.00  8.03
15           15                          목숨 건 연애  142263   7.53  4.00  4.31
16           16                         신비한 동물사전  115642   8.69  7.08  8.18
17           17                          캡틴 판타스틱  127396   8.97  7.50  8.71
18           18                              더 킹  144314   8.39  6.83  8.08
19           19                     매드맥스: 분노의 도로   77768   8.86  8.75  8.76
20           20                      나, 다니엘 블레이크  150376   9.28  8.40  9.25
21           21                            어카운턴트  134859   8.15  4.00  8.30
22           22          극장판 도라에몽:신 진구의 버스 오브 재팬  141675   8.95  0.00  9.04
23           23                            최후의 Z  102805  10.00  0.00  6.05
24           24                그 시절, 우리가 좋아했던 소녀   88669   9.14  6.00  9.02
25           25                     하이큐!! 승자와 패자  155963   9.27  0.00  9.03
26           26                        사다코 대 카야코  149283   6.74  2.50  5.83
27           27                     무현, 두 도시 이야기  152183   9.44  6.00  8.68
28           28                       내 남편의 가정교사  158788   0.00  0.00  6.90
29           29                     잭 리처: 네버 고 백  119412   8.13  4.88  7.15
..          ...                              ...     ...    ...   ...   ...
107         107                데이라이트 엔드: 인류멸망의 날  149829   0.00  0.00  0.00
108         108                  파이널 크루: 칸우 탈출작전  158402   0.00  0.00  8.81
109         109                       삼국지: 명장 관우   76794   0.00  6.00  7.31
110         110                               유혹  158464   0.00  0.00  3.46
111         111                      오텁시 오브 제인 도  154461   8.36  6.50  8.01
112         112            몽키킹 히어로: 손오공과 요괴왕의 대결  158743   0.00  0.00  6.28
113         113                           루시드 드림  130713   8.06  3.00  5.87
114         114                       드래곤: 용의 신부  154045   0.00  0.00  0.00
115         115                            핵소 고지  142305   9.19  6.00  9.20
116         116                               은하  138209   0.00  0.00  4.25
117         117                               해빙  137875   6.64  6.00  6.50
118         118                       트리플 엑스 리턴즈  102278   8.18  0.00  6.98
119         119                         23 아이덴티티  144927   7.94  6.50  7.65
120         120                             몬스터콜  125401   8.59  6.88  8.57
121         121                    돈키호테 맨 오브 라만차  130931   0.00  0.00  6.65
122         122                           그레이트 월  126034   7.92  4.50  6.45
123         123                               로건  117787   8.93  7.55  9.06
124         124                              라이언  134841   9.30  6.50  9.18
125         125        바다 탐험대 옥토넛 시즌4: 바다 괴물 대소동  158266   8.30  0.00  8.27
126         126                          400 데이즈  144433   0.00  0.00  0.00
127         127                              스플릿  146512   9.15  6.38  8.99
128         128                              용의자   93028   8.27  6.47  8.35
129         129                   키코리키: 황금모자의 비밀  148946   7.37  0.00  7.65
130         130                          맛있는 워킹걸  158764   0.00  0.00  3.67
131         131                        사운드 오브 뮤직   10102   9.60  0.00  9.39
132         132                             검사외전  130903   8.56  5.94  7.94
133         133                   미션 임파서블: 로그네이션   95541   8.81  7.54  8.75
134         134                               블랙   68567   9.42  6.93  9.04
135         135                 뚜르: 내 생애 최고의 49일  142304   9.51  6.20  9.25
136         136                   서유기3: 월광보합 리턴즈  142323   0.00  0.00  2.87

[137 rows x 6 columns]

In [69]:
df3

,movieCd,movieNm,director,Rate,Unnamed: 0,1,2,3,4
0,20161725,마스터,NaN,0,0.0,145162.0,8.65,5.77,8.10
1,20163183,로그 원: 스타워즈 스토리,NaN,0,1.0,136868.0,8.34,7.16,8.44
2,20162025,씽,NaN,0,3.0,144938.0,8.99,6.71,8.96
3,20144641,판도라,NaN,0,4.0,132933.0,8.78,5.92,8.31
4,20167904,라라랜드,NaN,0,2.0,134963.0,8.90,8.34,8.59
5,20161872,너의 이름은.,NaN,0,6.0,150198.0,9.02,7.55,8.75
6,20162727,루돌프와 많이있어,NaN,0,12.0,153951.0,8.73,6.38,8.80
7,20162183,포켓몬 더 무비 XY&Z 「볼케니온 : 기계왕국의 비밀」,NaN,0,13.0,152265.0,8.74,0.00,8.75
8,20152371,"당신, 거기 있어줄래요",NaN,0,5.0,145292.0,8.80,5.44,8.68
9,20165285,극장판 도라에몽: 신 진구의 버스 오브 재팬,NaN,0,NaN,NaN,NaN,NaN,NaN
10,19890291,해리가 샐리를 만났을 때,NaN,0,34.0,10250.0,7.75,8.50,8.90
11,20161763,"나, 다니엘 블레이크",NaN,0,20.0,150376.0,9.28,8.40,9.25
12,20163014,7년-그들이 없는 언론,NaN,0,70.0,146526.0,9.48,6.00,8.54
13,20161084,패신저스,NaN,0,8.0,116233.0,8.03,5.50,7.95
14,20150966,사랑하기 때문에,NaN,0,14.0,140010.0,8.39,6.00,8.03
15,20165153,눈의 여왕 3: 눈과 불의 마법대결,NaN,0,NaN,NaN,NaN,NaN,NaN
16,20151181,여교사,NaN,0,9.0,139673.0,7.31,6.78,6.61
17,20164421,어쌔신 크리드,NaN,0,30.0,118307.0,7.29,5.67,7.10
18,20168381,얼라이드,NaN,0,48.0,149777.0,8.58,6.50,8.86
19,20168324,반지의 제왕 : 반지원정대 (확장판),NaN,0,NaN,NaN,NaN,NaN,NaN
20,20165443,모아나,NaN,0,64.0,130849.0,9.22,6.40,9.15
21,20151229,더 킹,NaN,0,18.0,144314.0,8.39,6.83,8.08
22,20151228,공조,NaN,0,46.0,142384.0,8.83,5.00,8.27
23,20163845,터닝메카드W: 블랙미러의 부활,NaN,0,85.0,155484.0,8.87,0.00,8.73
24,20168664,반지의 제왕 : 두개의 탑 (확장판),NaN,0,NaN,NaN,NaN,NaN,NaN
25,20163186,단지 세상의 끝,NaN,0,88.0,137958.0,7.66,6.90,7.46
26,20168688,레지던트 이블: 파멸의 날,NaN,0,57.0,110333.0,8.59,6.00,8.38
27,20168154,딥워터 호라이즌,NaN,0,40.0,137346.0,8.77,6.50,8.05
28,20167285,짱구는 못말려 극장판: 폭풍수면! 꿈꾸는 세계 대돌격,NaN,0,105.0,149050.0,8.76,0.00,8.86
29,20168689,반지의 제왕 : 왕의 귀환 (확장판),NaN,0,NaN,NaN,NaN,NaN,NaN
30,20168366,바다 탐험대 옥토넛 시즌4: 바다 괴물 대소동,NaN,0,125.0,158266.0,8.30,0.00,8.27

In [70]:
df3['1'] == NaN

NameError: name 'NaN' is not defined

In [71]:
type(df3['1'][29])

numpy.float64

In [72]:
import numpy as np

In [ ]:
for i in range(len(df3['1'])):
    if(np.isnan(df3['1'][i])):
        print(str(i)+" NaN")
        name = df3['movieNm'][i][:-5].replace(' ','')
        print(name)
        for j in range(len(df2)):
            df2_name = df2['movieNm'][j].replace(' ','')
#             print(bool(df2_name == name[0:6]))
            print(df2_name)
            if(df2_name[0:8] == name[0:8]):
                print(df2_name[0:6])
                print(name[0:6])
                df3['Unnamed: 0'][i] = int(df2['Unnamed: 0'][j])
                df3['1'][i] = df2['1'][j]
                df3['2'][i] = df2['2'][j]
                df3['3'][i] = df2['3'][j]
                df3['4'][i] = df2['4'][j]

In [74]:
df3

,movieCd,movieNm,director,Rate,Unnamed: 0,1,2,3,4
0,20161725,마스터,NaN,0,0.0,145162.0,8.65,5.77,8.10
1,20163183,로그 원: 스타워즈 스토리,NaN,0,1.0,136868.0,8.34,7.16,8.44
2,20162025,씽,NaN,0,3.0,144938.0,8.99,6.71,8.96
3,20144641,판도라,NaN,0,4.0,132933.0,8.78,5.92,8.31
4,20167904,라라랜드,NaN,0,2.0,134963.0,8.90,8.34,8.59
5,20161872,너의 이름은.,NaN,0,6.0,150198.0,9.02,7.55,8.75
6,20162727,루돌프와 많이있어,NaN,0,12.0,153951.0,8.73,6.38,8.80
7,20162183,포켓몬 더 무비 XY&Z 「볼케니온 : 기계왕국의 비밀」,NaN,0,13.0,152265.0,8.74,0.00,8.75
8,20152371,"당신, 거기 있어줄래요",NaN,0,5.0,145292.0,8.80,5.44,8.68
9,20165285,극장판 도라에몽: 신 진구의 버스 오브 재팬,NaN,0,22.0,141675.0,8.95,0.00,9.04
10,19890291,해리가 샐리를 만났을 때,NaN,0,34.0,10250.0,7.75,8.50,8.90
11,20161763,"나, 다니엘 블레이크",NaN,0,20.0,150376.0,9.28,8.40,9.25
12,20163014,7년-그들이 없는 언론,NaN,0,70.0,146526.0,9.48,6.00,8.54
13,20161084,패신저스,NaN,0,8.0,116233.0,8.03,5.50,7.95
14,20150966,사랑하기 때문에,NaN,0,14.0,140010.0,8.39,6.00,8.03
15,20165153,눈의 여왕 3: 눈과 불의 마법대결,NaN,0,39.0,156675.0,8.34,0.00,8.57
16,20151181,여교사,NaN,0,9.0,139673.0,7.31,6.78,6.61
17,20164421,어쌔신 크리드,NaN,0,30.0,118307.0,7.29,5.67,7.10
18,20168381,얼라이드,NaN,0,48.0,149777.0,8.58,6.50,8.86
19,20168324,반지의 제왕 : 반지원정대 (확장판),NaN,0,56.0,31794.0,0.00,0.00,9.29
20,20165443,모아나,NaN,0,64.0,130849.0,9.22,6.40,9.15
21,20151229,더 킹,NaN,0,18.0,144314.0,8.39,6.83,8.08
22,20151228,공조,NaN,0,46.0,142384.0,8.83,5.00,8.27
23,20163845,터닝메카드W: 블랙미러의 부활,NaN,0,85.0,155484.0,8.87,0.00,8.73
24,20168664,반지의 제왕 : 두개의 탑 (확장판),NaN,0,94.0,31795.0,0.00,0.00,9.34
25,20163186,단지 세상의 끝,NaN,0,88.0,137958.0,7.66,6.90,7.46
26,20168688,레지던트 이블: 파멸의 날,NaN,0,57.0,110333.0,8.59,6.00,8.38
27,20168154,딥워터 호라이즌,NaN,0,40.0,137346.0,8.77,6.50,8.05
28,20167285,짱구는 못말려 극장판: 폭풍수면! 꿈꾸는 세계 대돌격,NaN,0,105.0,149050.0,8.76,0.00,8.86
29,20168689,반지의 제왕 : 왕의 귀환 (확장판),NaN,0,102.0,31796.0,0.00,0.00,9.37
30,20168366,바다 탐험대 옥토넛 시즌4: 바다 괴물 대소동,NaN,0,125.0,158266.0,8.30,0.00,8.27

In [61]:
df3['movieNm'][29]

'반지의 제왕 : 왕의 귀환 (확장판)'

In [75]:
df3.to_csv('movie_01.csv')